In [1]:
# importing packages
import numpy as np
import pandas as pd

In [2]:
# q1 pandas version
pd.__version__

'1.5.3'

In [3]:
# q2 records count
car_fuel_eff_df = pd.read_csv('car_fuel_efficiency.csv')
print(car_fuel_eff_df.head())
car_fuel_eff_df.shape

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3         

(9704, 11)

In [4]:
# q3 fuel types
print(car_fuel_eff_df['fuel_type'].unique())

['Gasoline' 'Diesel']


In [5]:
# q4 missing values
print((car_fuel_eff_df.isna().sum() > 0).sum())

4


In [6]:
# q5 max fuel efficiency
# for cars from asia
car_fuel_eff_df[car_fuel_eff_df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

In [7]:
# q6 median value of horsepower
# median value of horsepower before and after filling with most frequent value

# median horsepower before filling nulls
print('median horsepower (before filling null):', car_fuel_eff_df['horsepower'].median())

# most frequent value in horsepower column
most_freq_horsepower = car_fuel_eff_df['horsepower'].mode()[0]
print('most frequent (mode) horsepower (before filling null):', most_freq_horsepower)

# fill nulls with most frequent horsepower
car_fuel_eff_df['horsepower'] = car_fuel_eff_df['horsepower'].fillna(most_freq_horsepower)

# median horsepower after filling nulls
print('median horsepower (after filling null):', car_fuel_eff_df['horsepower'].median())

median horsepower (before filling null): 149.0
most frequent (mode) horsepower (before filling null): 152.0
median horsepower (after filling null): 152.0


* Median horsepower has changed from 149.0 to 152.0